from django.core.management.base import BaseCommand
from employees.models import Employee
from datetime import date

class Command(BaseCommand):
    help = 'Seeds database with realistic sample employee records'

    def handle(self, *args, **kwargs):
        self.stdout.write(self.style.WARNING('Seeding employee data...'))

        sample_employees = [
            {
                'employee_id': 'EMP-1001',
                'first_name': 'Eleanor',
                'last_name': 'Vance',
                'email': 'eleanor.vance@company.com',
                'phone': '+1 (555) 234-5678',
                'gender': 'Female',
                'date_of_birth': date(1992, 4, 15),
                'department': 'Software Development',
                'designation': 'Senior Developer',
                'joining_date': date(2021, 3, 10),
                'employment_type': 'Full Time',
                'salary': 115000.00,
                'address': '742 Evergreen Terrace',
                'city': 'San Francisco',
                'state': 'CA',
                'status': 'Active',
            },
            {
                'employee_id': 'EMP-1002',
                'first_name': 'Marcus',
                'last_name': 'Aurelius',
                'email': 'marcus.aurelius@company.com',
                'phone': '+1 (555) 345-6789',
                'gender': 'Male',
                'date_of_birth': date(1988, 8, 22),
                'department': 'Human Resources',
                'designation': 'Manager',
                'joining_date': date(2019, 6, 1),
                'employment_type': 'Full Time',
                'salary': 98000.00,
                'address': '100 Palatine Hill',
                'city': 'Austin',
                'state': 'TX',
                'status': 'Active',
            },
            {
                'employee_id': 'EMP-1003',
                'first_name': 'Sophia',
                'last_name': 'Chen',
                'email': 'sophia.chen@company.com',
                'phone': '+1 (555) 456-7890',
                'gender': 'Female',
                'date_of_birth': date(1995, 11, 3),
                'department': 'IT',
                'designation': 'Team Lead',
                'joining_date': date(2022, 1, 15),
                'employment_type': 'Full Time',
                'salary': 105000.00,
                'address': '55 Tech Boulevard',
                'city': 'Seattle',
                'state': 'WA',
                'status': 'Active',
            },
            {
                'employee_id': 'EMP-1004',
                'first_name': 'David',
                'last_name': 'Miller',
                'email': 'david.miller@company.com',
                'phone': '+1 (555) 567-8901',
                'gender': 'Male',
                'date_of_birth': date(1990, 2, 28),
                'department': 'Finance',
                'designation': 'Accountant',
                'joining_date': date(2020, 9, 14),
                'employment_type': 'Full Time',
                'salary': 85000.00,
                'address': '42 Wall Street',
                'city': 'New York',
                'state': 'NY',
                'status': 'On Leave',
            },
            {
                'employee_id': 'EMP-1005',
                'first_name': 'Amara',
                'last_name': 'Okafor',
                'email': 'amara.okafor@company.com',
                'phone': '+1 (555) 678-9012',
                'gender': 'Female',
                'date_of_birth': date(1997, 7, 19),
                'department': 'Marketing',
                'designation': 'Marketing Executive',
                'joining_date': date(2023, 2, 1),
                'employment_type': 'Contract',
                'salary': 72000.00,
                'address': '88 Sunset Blvd',
                'city': 'Los Angeles',
                'state': 'CA',
                'status': 'Active',
            },
            {
                'employee_id': 'EMP-1006',
                'first_name': 'Lucas',
                'last_name': 'Silva',
                'email': 'lucas.silva@company.com',
                'phone': '+1 (555) 789-0123',
                'gender': 'Male',
                'date_of_birth': date(1994, 5, 12),
                'department': 'Sales',
                'designation': 'Sales Executive',
                'joining_date': date(2022, 10, 5),
                'employment_type': 'Full Time',
                'salary': 78000.00,
                'address': '320 Commerce Way',
                'city': 'Chicago',
                'state': 'IL',
                'status': 'Inactive',
            },
            {
                'employee_id': 'EMP-1007',
                'first_name': 'Priya',
                'last_name': 'Sharma',
                'email': 'priya.sharma@company.com',
                'phone': '+1 (555) 890-1234',
                'gender': 'Female',
                'date_of_birth': date(1998, 12, 8),
                'department': 'Software Development',
                'designation': 'Developer',
                'joining_date': date(2023, 6, 20),
                'employment_type': 'Full Time',
                'salary': 92000.00,
                'address': '12 Innovation Way',
                'city': 'San Jose',
                'state': 'CA',
                'status': 'Active',
            },
            {
                'employee_id': 'EMP-1008',
                'first_name': 'Ethan',
                'last_name': 'Wright',
                'email': 'ethan.wright@company.com',
                'phone': '+1 (555) 901-2345',
                'gender': 'Male',
                'date_of_birth': date(2001, 9, 30),
                'department': 'Customer Support',
                'designation': 'Support Executive',
                'joining_date': date(2024, 1, 10),
                'employment_type': 'Intern',
                'salary': 45000.00,
                'address': '104 Campus Drive',
                'city': 'Denver',
                'state': 'CO',
                'status': 'Active',
            },
            {
                'employee_id': 'EMP-1009',
                'first_name': 'Rachel',
                'last_name': 'Green',
                'email': 'rachel.green@company.com',
                'phone': '+1 (555) 012-3456',
                'gender': 'Female',
                'date_of_birth': date(1993, 3, 25),
                'department': 'Administration',
                'designation': 'HR Executive',
                'joining_date': date(2021, 11, 12),
                'employment_type': 'Part Time',
                'salary': 55000.00,
                'address': '90 Central Park West',
                'city': 'New York',
                'state': 'NY',
                'status': 'Active',
            },
            {
                'employee_id': 'EMP-1010',
                'first_name': 'James',
                'last_name': 'Wilson',
                'email': 'james.wilson@company.com',
                'phone': '+1 (555) 123-4567',
                'gender': 'Male',
                'date_of_birth': date(1986, 10, 5),
                'department': 'Operations',
                'designation': 'Manager',
                'joining_date': date(2018, 4, 1),
                'employment_type': 'Full Time',
                'salary': 120000.00,
                'address': '500 Logistics Way',
                'city': 'Atlanta',
                'state': 'GA',
                'status': 'Active',
            },
        ]

        created_count = 0
        for data in sample_employees:
            emp, created = Employee.objects.get_or_create(
                employee_id=data['employee_id'],
                defaults=data
            )
            if created:
                created_count += 1

        self.stdout.write(self.style.SUCCESS(f'Successfully seeded {created_count} new sample employees (Total in DB: {Employee.objects.count()}).'))
